Workdir behavior changed and add target input
tsuyoshicho/action-mypy pull request #12
Opened 2021-01-17 16:28 UTC by Milly

## related issue

no

## Fix or Add this PR/このプルリクエストでやったこと

- `workdir` changes current directory. Now, this is not a target directory.
  - This is **breaking change**. Must be update version to v2.
- `target` is added. This is the target path of mypy command. 
- Added tests for above.
- *.mypy_cache/* is added to *.gitignore*. (for testing in local)

## Not fix or add this PR/このプルリクエストでやらなかったこと

no

## Pros and Cons/メリットとデメリット

Because *mypy.ini* is only used at the current directory.
If *mypy.ini* is exists in the sub-directory, can not detect errors.

## Test/動作確認

- [ ] The tests fails, before modifying the code. (*jobs.test-local.steps.mypy-local-error-should-failure* should failed)
- [ ] The tests success, after modifying the code. (All of *jobs.test-local* should succeeded)

2021-01-17 16:33 UTC, Milly commented
適切な semantic PR title はなんでしょうね……

2021-01-18 00:42 UTC, tsuyoshicho commented
LGTM! (とりあえず見た限り)

後で詳細に確認します。

> 適切な semantic PR title はなんでしょうね……

feat: かな? まあ、これは満せてなくてもマージ判断には加えませんからw (あくまでコミットログ他のためにやってるだけで、必須ではないつもりです)

2021-01-18 12:42 UTC, tsuyoshicho requested changes
Please Update README for this change.

- add sample and param
- not need v1 and v2 differences point/wrote "workdir" change current dir info

---

上記が追記できたらmajor verup としてマージします。

2021-01-18 16:03 UTC, Milly commented
README and description in *action.yml* are changed.

2021-01-18 22:56 UTC, tsuyoshicho approved these changes

2021-01-18 22:56 UTC, tsuyoshicho commented on README.md
> +          # mypy commmand reads setup.cfg or other settings file in this path.
```suggestion
          # mypy command reads setup.cfg or other settings file in this path.
```

2021-01-18 22:59 UTC, merged

2021-01-18 23:00 UTC, tsuyoshicho commented
Thank you for your contribution!

2021-01-19 01:33 UTC, Milly commented on README.md
> +          # mypy commmand reads setup.cfg or other settings file in this path.
Oh. sorry